/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMemoriesRouteImport } from './routes/_app/memories'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppCIdRouteImport } from './routes/_app/c.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppCIdRoute = AppCIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/memories': typeof AppMemoriesRoute
  '/c/$id': typeof AppCIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/memories': typeof AppMemoriesRoute
  '/': typeof AppIndexRoute
  '/c/$id': typeof AppCIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/memories': typeof AppMemoriesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/c/$id': typeof AppCIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/knowledge' | '/memories' | '/c/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/knowledge' | '/memories' | '/' | '/c/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/knowledge'
    | '/_app/memories'
    | '/_app/'
    | '/_app/c/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/c/$id': {
      id: '/_app/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof AppCIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCIdRoute: typeof AppCIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppMemoriesRoute: AppMemoriesRoute,
  AppIndexRoute: AppIndexRoute,
  AppCIdRoute: AppCIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
